repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
        exclude: drafts
      - id: trailing-whitespace
        exclude: ^(docs/|drafts/)`
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: pretty-format-json
        args: ["--autofix"]
      - id: debug-statements
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
