name: Publish new post

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Render html-based post from markdown
      run: |-
        python build.py

    - name: Deploy
      run: |-
        git diff
        git config --global user.email "bot@hung.codes"
        git config --global user.name "Hung's bot"
        git diff --quiet || (
          changed_files=$(git diff --name-only srcs)
          git add docs
          git commit -m "Publish new post: $changed_files"
        )
        git push
